### ISSUE TITLE
Add support for yaml-patch

### ISSUE THREAD

**Issue by patrickdappollonio** [patrickdappollonio/kubectl-slice#15]
It would be cool if the tool would support patching the YAML data using [`yaml-patch`](https://github.com/pivotal-cf/yaml-patch).

A good example would be adding an annotation to all resources, like `github.com/patrickdappollonio/kubectl-slice: "true"`:

```yaml
$ cat input.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-ingress
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
```

```yaml
$ cat patch.yaml
- op: add
  path: /metadata/annotations
  value: {}
- op: add
  path: /metadata/annotations/github.com~1patrickdappollonio~1kubectl-slice
  value: "true"
```

Then running `kubectl-slice` will render the files:

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    github.com/patrickdappollonio/kubectl-slice: "true"
  name: nginx-ingress
```

```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    github.com/patrickdappollonio/kubectl-slice: "true"
  name: production
```

Some unknowns though:

**FIRST.** If patching fails, do we error out? Do we warn and continue? A good example above is that our patch first needed to add the annotation otherwise it would've failed if we try to add the annotation directly, without creating the node first: 
```
yamlpatch add operation does not apply: doc is missing path: /metadata/annotations/github.com~1patrickdappollonio~1kubectl-slice
```

**SECOND.** Do we apply filters _before_ or _after_ patching? For example, you could have a resource that doesn't have a `kind: Foo` but a patch that adds it. If you use `--include-kind Foo` then this resource would be added **only** after the patch is executed. So we need to decide if we patch-then-filter or filter-then-patch.

**Comment by patrickdappollonio** [comment]
As a feedback for the second point, I think it would be good if you filter-then-patch. The argument could be that you don't call `kubectl-slice` wanting to patch resources. You could pre-patch using other tools, pipe to `kubectl-slice`, then patch after filtering.

That, or I add a `--prepatch` and/or `--postpatch`. 😋

**Comment by patrickdappollonio** [comment]
Another thought: in order to be able to process multiple resources, rather than simply providing the patch, we should provide something similar to `kustomize` YAML:

```bash
- patches:
  - op: <op>
    path: <json-path>
    value: <object>
  target:
    kind: <optional kind>
    name: <optional name>
```

For example, to rename the `ingress-nginx` above and add the annotation:

```
$ cat pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-ingress

$ cat patch.yaml
- patches:
  - op: replace
    path: /metadata/name
    value: new-ingress-nginx
  - op: add
    path: /metadata/annotations
    value: {}
  - op: add
    path: /metadata/annotations/github.com~1patrickdappollonio~1kubectl-slice
    value: "true"
  target:
    kind: Pod
    name: ingress-nginx
```

If you would rather still target all objects, you could do (note the lack of a target):

```
- patches:
  - op: add
    path: /metadata/annotations
    value: {}
  - op: add
    path: /metadata/annotations/github.com~1patrickdappollonio~1kubectl-slice
    value: "true"
```
