### ISSUE TITLE
Multi-file yamls where the first file is commented results in an awkward parse

### ISSUE THREAD

**Issue by patrickdappollonio** [patrickdappollonio/kubectl-slice#3]
### What did you do?

Tried to split this file:

```yaml
# foo bar baz
# a b c
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-docker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-docker-app
  template:
    metadata:
      labels:
        app: hello-docker-app
    spec:
      containers:
        - name: hello-docker-container
          image: patrickdappollonio/hello-docker

```

### What did you expect to see?

```
$ kubectl-split -f stack.yaml
Wrote deployment-hello-docker.yaml -- 332 bytes.
1 file generated.
```

One file generated since the other one seems to be just comments.

### What did you see instead?

```
$ kubectl-split -f stack.yaml
Wrote -.yaml -- 22 bytes.
Wrote deployment-hello-docker.yaml -- 332 bytes.
2 files generated.
```

It's very common for Kubernetes YAMLs to have at least one comment out. The behaviour of the app here makes sense: if you open the `-.yaml` file you'll see the YAML was split and this file in particular contains:

```yaml
# foo bar baz
# a b c
```

Technically it is the correct split: two files, one with the first YAML, and another with the second one, maintaining all comments from the original. The name is "botched" just because the template used by default would render no data for `{{.kind | lower}}-{{.metadata.name}}.yaml` keeping just the dash.

The questions here are: 

* Do we correct the parser to exclude splitting a file that's all comments (or potentially comments + random, non-Kubernetes YAML)?; or
* do we keep the behaviour as-is, but add a validation or a warning that if the file name generated does not contain 1+ alphanumeric characters (as a sign of good faith since a file named `-.yaml` has probably no use) then warn, and potentially a mode that refuses to run if files have this warning?; or
* do we strictly enforce that, since this is a Kubernetes-specific tool, all files must have at least `apiVersion`, `kind` and `metadata.name`?; or
* do we keep the behaviour as-is since it's technically correct, but fix the default file name template `{{.kind | lower}}-{{.metadata.name}}.yaml`?; or
* do we keep the behaviour as-is since it's technically correct, and not fix the default file name nor skip the entirely commented file?

Asking for public feedback, since I don't have a strong opinion on this.
