### ISSUE TITLE
Add support for a configuration file

### ISSUE THREAD

**Issue by patrickdappollonio** [patrickdappollonio/kubectl-slice#66]
It would be useful for multiple case scenarios to support a configuration file instead of passing `kubectl-slice` settings via arguments. Arguments are not only cumbersome if they become long, but certain special characters that might be part of an argument might be handled differently per shell interpreter (see #53).

A proposal was made in #53 to include a "configuration file". To start, this file could be a YAML file with the name of `.kubectl-slice.yaml` in the current working directory (the dot being so it's treated as configuration). By default, the configuration file can be read from the current working directory, but optionally, it could be specified using `--configuration /path/to/config.yaml` which will allow not only to host the file in a place other than the current working directory but also rename the file to whatever the end user would prefer.

The configuration file could use `viper` (which plays well with `spf13/cobra`) to configure these settings from a file matching all the currently supported flags, and by using their exact same name as YAML arguments although in their long flag name form: https://github.com/patrickdappollonio/kubectl-slice/blob/ca0638a4c658d3748f65bc47ab9914fa9781cc6d/app.go#L75-L89

(I've done a similar thing in `http-server`, [here](https://github.com/patrickdappollonio/http-server/blob/e6547ab51ee06544c7493e99769bc0a71dd8c0ba/app.go#L146-L210))

Opening this issue for two reasons: a) track the progress of this change; but b) ensure people can provide feedback. Namely, the format of the current file would look like this:

```yaml
input_file: string
output_dir: string
template: string
dry_run: bool
debug: bool
quiet: bool
include_kind: []string
exclude_kind: []string
include_name: []string
exclude_name: []string
include: []string
exclude: []string
skip_non_k8s: bool
sort_by_kind: bool
stdout: bool
```

However an argument could be made that the format might differ from the flags into additional options (see https://github.com/patrickdappollonio/kubectl-slice/issues/53#issuecomment-1173130975 for an example).

Opening this for feedback. I'll wait a reasonable amount of time to implement this behaviour to make sure feedback is captured (or no feedback at all if it's been too long since opened with no comments).
